//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewUI.DistrictSrv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistrictSrv.IDistrictService")]
    public interface IDistrictService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/addDistrict", ReplyAction="http://tempuri.org/IDistrictService/addDistrictResponse")]
        int addDistrict(int districtId, int primarySalePersonId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/addDistrict", ReplyAction="http://tempuri.org/IDistrictService/addDistrictResponse")]
        System.Threading.Tasks.Task<int> addDistrictAsync(int districtId, int primarySalePersonId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/getAllDistricts", ReplyAction="http://tempuri.org/IDistrictService/getAllDistrictsResponse")]
        InterviewService.District[] getAllDistricts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/getAllDistricts", ReplyAction="http://tempuri.org/IDistrictService/getAllDistrictsResponse")]
        System.Threading.Tasks.Task<InterviewService.District[]> getAllDistrictsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/changePrimarySalesPerson", ReplyAction="http://tempuri.org/IDistrictService/changePrimarySalesPersonResponse")]
        int changePrimarySalesPerson(int districtid, int primeSalePersId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/changePrimarySalesPerson", ReplyAction="http://tempuri.org/IDistrictService/changePrimarySalesPersonResponse")]
        System.Threading.Tasks.Task<int> changePrimarySalesPersonAsync(int districtid, int primeSalePersId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/getDistrictSalePersons", ReplyAction="http://tempuri.org/IDistrictService/getDistrictSalePersonsResponse")]
        InterviewService.SalePerson[] getDistrictSalePersons(int districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/getDistrictSalePersons", ReplyAction="http://tempuri.org/IDistrictService/getDistrictSalePersonsResponse")]
        System.Threading.Tasks.Task<InterviewService.SalePerson[]> getDistrictSalePersonsAsync(int districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/getStoresOnDistrict", ReplyAction="http://tempuri.org/IDistrictService/getStoresOnDistrictResponse")]
        InterviewService.Store[] getStoresOnDistrict(int districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistrictService/getStoresOnDistrict", ReplyAction="http://tempuri.org/IDistrictService/getStoresOnDistrictResponse")]
        System.Threading.Tasks.Task<InterviewService.Store[]> getStoresOnDistrictAsync(int districtId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistrictServiceChannel : InterviewUI.DistrictSrv.IDistrictService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistrictServiceClient : System.ServiceModel.ClientBase<InterviewUI.DistrictSrv.IDistrictService>, InterviewUI.DistrictSrv.IDistrictService {
        
        public DistrictServiceClient() {
        }
        
        public DistrictServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistrictServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistrictServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistrictServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int addDistrict(int districtId, int primarySalePersonId, string name) {
            return base.Channel.addDistrict(districtId, primarySalePersonId, name);
        }
        
        public System.Threading.Tasks.Task<int> addDistrictAsync(int districtId, int primarySalePersonId, string name) {
            return base.Channel.addDistrictAsync(districtId, primarySalePersonId, name);
        }
        
        public InterviewService.District[] getAllDistricts() {
            return base.Channel.getAllDistricts();
        }
        
        public System.Threading.Tasks.Task<InterviewService.District[]> getAllDistrictsAsync() {
            return base.Channel.getAllDistrictsAsync();
        }
        
        public int changePrimarySalesPerson(int districtid, int primeSalePersId) {
            return base.Channel.changePrimarySalesPerson(districtid, primeSalePersId);
        }
        
        public System.Threading.Tasks.Task<int> changePrimarySalesPersonAsync(int districtid, int primeSalePersId) {
            return base.Channel.changePrimarySalesPersonAsync(districtid, primeSalePersId);
        }
        
        public InterviewService.SalePerson[] getDistrictSalePersons(int districtId) {
            return base.Channel.getDistrictSalePersons(districtId);
        }
        
        public System.Threading.Tasks.Task<InterviewService.SalePerson[]> getDistrictSalePersonsAsync(int districtId) {
            return base.Channel.getDistrictSalePersonsAsync(districtId);
        }
        
        public InterviewService.Store[] getStoresOnDistrict(int districtId) {
            return base.Channel.getStoresOnDistrict(districtId);
        }
        
        public System.Threading.Tasks.Task<InterviewService.Store[]> getStoresOnDistrictAsync(int districtId) {
            return base.Channel.getStoresOnDistrictAsync(districtId);
        }
    }
}
