//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewUI.AssignedPersonSrv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AssignedPersonSrv.IAssignedSalePersonService")]
    public interface IAssignedSalePersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignedSalePersonService/assignSalePerson", ReplyAction="http://tempuri.org/IAssignedSalePersonService/assignSalePersonResponse")]
        int assignSalePerson(int salePersonId, int districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignedSalePersonService/assignSalePerson", ReplyAction="http://tempuri.org/IAssignedSalePersonService/assignSalePersonResponse")]
        System.Threading.Tasks.Task<int> assignSalePersonAsync(int salePersonId, int districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignedSalePersonService/deleteAssignedPerson", ReplyAction="http://tempuri.org/IAssignedSalePersonService/deleteAssignedPersonResponse")]
        int deleteAssignedPerson(int salePersonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignedSalePersonService/deleteAssignedPerson", ReplyAction="http://tempuri.org/IAssignedSalePersonService/deleteAssignedPersonResponse")]
        System.Threading.Tasks.Task<int> deleteAssignedPersonAsync(int salePersonId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssignedSalePersonServiceChannel : InterviewUI.AssignedPersonSrv.IAssignedSalePersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssignedSalePersonServiceClient : System.ServiceModel.ClientBase<InterviewUI.AssignedPersonSrv.IAssignedSalePersonService>, InterviewUI.AssignedPersonSrv.IAssignedSalePersonService {
        
        public AssignedSalePersonServiceClient() {
        }
        
        public AssignedSalePersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssignedSalePersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssignedSalePersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssignedSalePersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int assignSalePerson(int salePersonId, int districtId) {
            return base.Channel.assignSalePerson(salePersonId, districtId);
        }
        
        public System.Threading.Tasks.Task<int> assignSalePersonAsync(int salePersonId, int districtId) {
            return base.Channel.assignSalePersonAsync(salePersonId, districtId);
        }
        
        public int deleteAssignedPerson(int salePersonId) {
            return base.Channel.deleteAssignedPerson(salePersonId);
        }
        
        public System.Threading.Tasks.Task<int> deleteAssignedPersonAsync(int salePersonId) {
            return base.Channel.deleteAssignedPersonAsync(salePersonId);
        }
    }
}
